FROM golang:1.4.2-cross

# TODO: Vendor these `go get` commands using Godep.
RUN go get github.com/mitchellh/gox
RUN go get github.com/tools/godep
RUN go get golang.org/x/tools/cmd/cover

ENV GOPATH /go/src/github.com/ekristen/docker-event-bridge/Godeps/_workspace:/go
ENV USER root

WORKDIR /go/src/github.com/ekristen/docker-event-bridge

ADD . /go/src/github.com/ekristen/docker-event-bridge
